name: plasmabio-template-bash
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # Bash environment
  - python>=3.8
  - pip
  - pip:
    - bash_kernel
